export const cQuizData = () => {
  return [
    {
      quiz_id: 1,
      question: "How are you",
      v1: "Akshay",
      v2: "Binod",
      v3: "Kamlesh",
      v4: "DJ Navid",
      correctAns: "Akshay",
      userAns: "",
    },
    {
      quiz_id: 2,
      question: "I am Fine BRO",
      v1: "Akshay JI",
      v2: "Binod IJ",
      v3: "Kamlesh J",
      v4: "DJ Navid JI",
      correctAns: "Akshay JI",
      userAns: "",
    },
    {
      quiz_id: 3,
      question: "I am Fine BRO",
      v1: "Akshay JI3",
      v2: "Binod3",
      v3: "Kamlesh J",
      v4: "DJ Navid JI",
      correctAns: "Akshay JI3",
      userAns: "",
    },
    {
      quiz_id: 4,
      question: "I am Fine BRO",
      v1: "Akshay JI4",
      v2: "Binod IJ",
      v3: "Kamlesh J",
      v4: "DJ Navid JI",
      correctAns: "Akshay JI4",
      userAns: "",
    },
    {
      quiz_id: 5,
      question: "I am Fine BRO",
      v1: "Akshay JI5",
      v2: "Binod IJ",
      v3: "Kamlesh J",
      v4: "DJ Navid JI",
      correctAns: "Akshay JI5",
      userAns: "",
    },
    {
      quiz_id: 6,
      question: "I am Fine BRO",
      v1: "Akshay JI6",
      v2: "Binod IJ",
      v3: "Kamlesh J",
      v4: "DJ Navid JI",
      correctAns: "Akshay JI6",
      userAns: "",
    },
    {
      quiz_id: 8,
      question: "I am Fine BRO",
      v1: "Akshay JI8",
      v2: "Binod IJ",
      v3: "Kamlesh J",
      v4: "DJ Navid JI",
      correctAns: "Akshay JI8",
      userAns: "",
    },
    {
      quiz_id: 9,
      question: "I am Fine BRO",
      v1: "Akshay JI9",
      v2: "Binod IJ",
      v3: "Kamlesh J",
      v4: "DJ Navid JI",
      correctAns: "Akshay JI9",
      userAns: "",
    },
  ];
};
